name: Auto-GPT-Action
description: A GitHub Action that uses runs Auto-GPT to follow instructions in the issue description.
author: Finn Fitzsimons

# branding:
#   color: '${{ github.action.color }}'
#   icon: '${{ github.action.icon }}'

inputs:
  openai_key:
    description: The OpenAI API key.
    required: true
    type: string
  github_token:
    description: Github API key.
    required: true
    type: string
  issue_body:
    description: The body of the issue.
    required: true
    type: string
    default: Create a new readme file in the repository root explaining quantum computing basics. # TODO remove
  issue_number:
    description: The number of the issue.
    required: true
    type: string
    default: "1" # TODO remove
  repository:
    description: The owner and repository name. For example, octocat/Hello-World.
    required: true
    type: string
  repository_name:
    description: The repository name. For example, Hello-World.
    required: true
    type: string
  project_description:
    description: Description of the service repository, its structure, technologies used, and what it does.
    required: true
    type: string
  ref_name:
    description: The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, feature-branch-1.
    required: true
    type: string
  ai_role:
    description: The role of the AI.
    type: string
    default: I want you to act as a software developer who is willing to review the issue described and commit appropriate fixes on a feature branch. When files are mentioned in the goals you will check to see if they exist, and modify them as necessary instead of creating new files. You will run the tests and iterate until all tests pass and then you will exit.  

outputs:
  commit_message:
    description: 'The commit message generated by Auto-GPT.'
  comment_message:
    description: 'The comment message generated by Auto-GPT-Action.'

runs:
  using: "composite"
  steps:

    - name: Checkout autodev
      uses: actions/checkout@v3
      with:
        repository: printify/autodev
        ref: finn2

    - name: Setup instructions
      shell: bash
      working-directory: ./
      run: |
        touch ai_settings.yaml
        printf "\nai_name: Autodev\nai_role: I want you to act as a software engineer.\nai_goals:\n- List the files in the container\- Inside the svc directory (but maybe some other directory) there is a GIT software repository cloned from ${{ inputs.repository }} which is a ${{ inputs.project_description }}. Your task is to first list all files and directorys in the container, then do the following: ${{ inputs.issue_body }}. All code/logic changes should be covered with tests and all tests should pass. You should modify existing files where possible before creating new ones. Try to follow existing patterns within the codebase. Give a summary of what you did as output." > ai_settings.yaml

    - name: Setup env
      shell: bash
      working-directory: ./
      run: |
        touch ".env"
        printf "OPENAI_API_KEY=${{ inputs.openai_key }}" > ".env"

    - name: Checkout External Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.github_token }}
        path: ./svc/${{ inputs.repository_name }}
        # ref: ${{ inputs.ref_name }}

    # - name: Install plugins
    #   shell: bash
    #   working-directory: ./autogpts/autogpt/
    #   run: |
    #     curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip

    # - name: debug
    #   shell: bash
    #   working-directory: ./
    #   run: |
    #     ls
    #     cat ".env"
    #     pwd
    #     echo $(pwd)/svc
    #     echo ${{env.GITHUB_ACTION_PATH}}
    #     echo "============================"
    
    - name: Run AutoGPT
      shell: bash
      working-directory: ./
      env:
        OPENAI_API_KEY: ${{ inputs.openai_key }}
      run: |
        docker pull significantgravitas/auto-gpt
        docker compose run --volume $(pwd)/svc --rm auto-gpt --continuous --continuous-limit 40 --ai-settings ./ai_settings.yaml

    - name: Commit changes
      shell: bash
      working-directory: ./svc/${{ inputs.repository_name }}
      run: |
        ls
        git status
        git config --global user.email 'github-actions@github.com'
        git config --global user.name 'Autodev'
        git add -A
        git commit -m "Autodev: resolve issue #${{ inputs.issue_number }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        path: ./data/${{ inputs.repository_name }}
        github_token: ${{ inputs.github_token }}
        branch: autodev/${{ inputs.issue_number }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        path: ./svc/${{ inputs.repository_name }}
        token: ${{ inputs.github_token }}
        branch: autodev/${{ inputs.issue_number }}

    # - name: Update issue
    #   uses: peter-evans/create-or-update-comment@v1
    #   with:
    #     issue-number: ${{ github.event.issue.number }}
    #     body: ${{ steps.run-autodev.outputs.comment_message }}