name: Auto-GPT-Action
description: A GitHub Action that uses runs Auto-GPT to follow instructions in the issue description.
author: Finn Fitzsimons

# branding:
#   color: '${{ github.action.color }}'
#   icon: '${{ github.action.icon }}'

inputs:
  openai_key:
    description: The OpenAI API key.
    required: true
    type: string
  issue_body:
    description: The body of the issue.
    required: true
    type: string
  issue_number:
    description: The number of the issue.
    required: true
    type: string
  ai_role:
    description: The role of the AI.
    type: string
    default: I want you to act as a software developer who is willing to review the issue described and commit appropriate fixes on a feature branch. When files are mentioned in the goals you will check to see if they exist, and modify them as necessary instead of creating new files. You will run the tests and iterate until all tests pass and then you will exit.  

outputs:
  commit_message:
    description: 'The commit message generated by Auto-GPT.'
  comment_message:
    description: 'The comment message generated by Auto-GPT-Action.'

jobs:
  run:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     agent-name: [ autogpt ]
    #   fail-fast: false
    timeout-minutes: 10
    # env:
    #   min-python-version: '3.10'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          repository: Significant-Gravitas/AutoGPT

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        working-directory: ./autogpts/autogpt/
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Run agent
        run: |
          ./run agent start autogpt
          cd autogpts/autogpt
        # poetry run agbenchmark --mock
        # poetry run agbenchmark --test=WriteFile
        env:
          OPENAI_API_KEY: ${{ github.event.inputs.openai_key }}
          AGENT_NAME: autogpt
          # HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
          # REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
          # HELICONE_CACHE_ENABLED: false
          # HELICONE_PROPERTY_AGENT: autogpt
          # REPORT_LOCATION: ${{ format('../../reports/{0}', matrix.agent-name) }}