name: Auto-GPT-Action
description: A GitHub Action that uses runs Auto-GPT to follow instructions in the issue description.
author: Finn Fitzsimons

# branding:
#   color: '${{ github.action.color }}'
#   icon: '${{ github.action.icon }}'

on:
  workflow_call:
    inputs:
      openai_key:
        description: The OpenAI API key.
        required: true
      issue_body:
        description: The body of the issue.
        required: true
      issue_number:
        description: The number of the issue.
        required: true
      ai_role:
        description: The role of the AI.
        default: I want you to act as a software developer who is willing to review the issue described and commit appropriate fixes on a feature branch. When files are mentioned in the goals you will check to see if they exist, and modify them as necessary instead of creating new files. You will run the tests and iterate until all tests pass and then you will exit.  

    outputs:
      commit_message:
        description: 'The commit message generated by Auto-GPT.'
      comment_message:
        description: 'The comment message generated by Auto-GPT-Action.'

jobs:
  autodev:
    runs-on: ubuntu-latest
    steps:
    runs:
      using: 'docker'
      image: 'finnfiddle/auto-gpt-action'
      args: 
        - ai_role: "${{ github.event.inputs.ai_role }}"
        - openai_key: "${{ github.event.inputs.openai_key }}"
        - issue_body: '${{ github.event.inputs.issue_body }}'
        - issue_number: '${{ github.event.inputs.issue_number }}'
